
# input: a dtf of count table, a dtf of design table, a vector of selected sample lables, a string of selected gene column name
# output: a dtf selected count table with column "gene", "selected sample label 1", "selected sample label 2", .. same order as in sample.labels
# function uses the sample lable vector, find the coresponding sample names in info table and selected these samples together with the gene column from the count table. 
match.ct.info <- function(ct, design, sample.labels, gene){
  sample.names <- design$`Sample Name`[match(sample.labels, design$`Sample Label`)]
  if(any(!(sample.names %in% colnames(ct)))) stop("Sample names in the design table are not found in count table")
  ct.selected <- ct[, c(gene, sample.names)]
  colnames(ct.selected) <- c("gene", sample.labels)
  return(ct.selected)
}


# input: a data table generated by DEGexp, q_value, fold_change
# output: the data table added with column "mu", "clr", "pch" for MA plot
add.clm <- function(dt.tb, q_value, fold_change){
  dt.tb[ , mu := ifelse(value1 != 0 & value2 != 0,
                        (log2(value1) + log2(value2))/2,
                        ifelse(value1 != 0 & value2 == 0,
                               (log2(value1) + log2(value2+1))/2,
                               ifelse(value1 == 0 & value2 != 0,
                                      (log2(value1 + 1) + log2(value2))/2,
                                      (log2(value1 + 1) + log2(value2 + 1))/2)))
         ]
  dt.tb$clr <- "black"
  dt.tb$clr[dt.tb$`q-value(Storey et al. 2003)` < as.numeric(q_value)] <- "purple"
  dt.tb$clr[dt.tb$`q-value(Storey et al. 2003)` < as.numeric(q_value)
            & abs(dt.tb$`log2(Fold_change) normalized`) >= as.numeric(fold_change)] <- "red"
  dt.tb$pch <- 46
  dt.tb$pch[dt.tb$`q-value(Storey et al. 2003)` < as.numeric(q_value)] <- 3
  dt.tb$pch[dt.tb$`q-value(Storey et al. 2003)` < as.numeric(q_value)
            & abs(dt.tb$`log2(Fold_change) normalized`) >= as.numeric(fold_change)] <- 4
  dt.tb$pch <- factor(dt.tb$pch,levels = c(46, 3, 4))
  
  return(dt.tb)
}


# change in gene expression
# input: two data tables generated by DEGexp (trt2_trt1 and trt3_trt2), q_value, fold_change
# output: a list including vectors of gene names for trt2_trt1_up, trt2_trt1_dn, trt3_trt2_up, trt3_trt2_dn, up.dn, dn.up, and a data table of intersection genes and it's logfolcchange
cige <- function(table_trt2_trt1, table_trt3_trt2, q_value, fold_change){
  trt2_trt1_up <- table_trt2_trt1[table_trt2_trt1$`q-value(Storey et al. 2003)` < as.numeric(q_value)
                                  & table_trt2_trt1$`log2(Fold_change)` >= as.numeric(fold_change), ]$GeneNames
  trt2_trt1_dn <- table_trt2_trt1[table_trt2_trt1$`q-value(Storey et al. 2003)` < as.numeric(q_value) 
                                  & table_trt2_trt1$`log2(Fold_change)` <= -as.numeric(fold_change), ]$GeneNames
  trt3_trt2_up <- table_trt3_trt2[table_trt3_trt2$`q-value(Storey et al. 2003)` < as.numeric(q_value) 
                                  & table_trt3_trt2$`log2(Fold_change)` >= as.numeric(fold_change), ]$GeneNames
  trt3_trt2_dn <- table_trt3_trt2[table_trt3_trt2$`q-value(Storey et al. 2003)` < as.numeric(q_value) 
                                  & table_trt3_trt2$`log2(Fold_change)` <= -as.numeric(fold_change), ]$GeneNames
  
  up.dn <- trt2_trt1_up[trt2_trt1_up %in% trt3_trt2_dn]
  dn.up <- trt2_trt1_dn[trt2_trt1_dn %in% trt3_trt2_up]
  
  up.dn_dn.up_genes <- unique(c(up.dn, dn.up))
  
  merge1  <- table_trt2_trt1[table_trt2_trt1$GeneNames %in% up.dn_dn.up_genes, c("GeneNames","log2(Fold_change) normalized")]
  merge2  <- table_trt3_trt2[table_trt3_trt2$GeneNames %in% up.dn_dn.up_genes, c("GeneNames","log2(Fold_change) normalized")]
  
  up.dn_dn.up_table <- merge(merge1, merge2, by = "GeneNames")
  up.dn_dn.up_table <- up.dn_dn.up_table[order(up.dn_dn.up_table[ ,2], decreasing = TRUE), ]
  cige <- list(trt2_trt1_up = trt2_trt1_up, 
               trt2_trt1_dn = trt2_trt1_dn, 
               trt3_trt2_up = trt3_trt2_up, 
               trt3_trt2_dn = trt3_trt2_dn,
               up.dn = up.dn,
               dn.up = dn.up,
               up.dn_dn.up_table = up.dn_dn.up_table)
  return(cige)
}